[program:jamur-iot-mqtt]
command=/usr/bin/php /www/wwwroot/jamur-iot.mazkama.web.id/artisan mqtt:subscribe
directory=/www/wwwroot/jamur-iot.mazkama.web.id
autostart=true
autorestart=true
startretries=3
numprocs=1
user=www-data
redirect_stderr=true
stdout_logfile=/www/wwwroot/jamur-iot.mazkama.web.id/storage/logs/mqtt-subscriber.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
